### ISSUE TITLE
network commands hang with kernel 5.16git

### ISSUE THREAD

**Issue by pierro78** [lwfinger/rtl8723du#11]
I tried (see https://forum.chuwi.com/t/linux-on-chuwi-gemibook/24770/25 ) to compile the module on the linux 5.16git kernel but then a command like "ip a" hangs and my desktop environment (I am on debian 11/antixlinux 21) would also hang ... "ip a" would tell me "INFO: task worker/u8:3:54 blocked for more than 120 seconds" but would not return ...

Maybe I also didn't compile the 5.16 kernel right (I am not knowledgeable with that) ...

**Comment by lwfinger** [comment]
The locking changed in the kernel leading to a deadlock. That is now fixed for both branches. Sorry, it took a while to actually find the reason for the deadlock.
