### ISSUE TITLE
[Question] what is the expected maintenance time for this driver?

### ISSUE THREAD

**Issue by Aqa-Ib** [lwfinger/rtl8723du#16]
Hello, how are you doing? fine? :D
I am thinking about getting a laptop with this chip and I want to know if I can expect using it on linux in the future or not.
Thank you very much for the work.
Cheers !!

**Comment by lwfinger** [comment]
I will keep maintaining it as long as I can; however, I am 81 years old! I expect that someone else will maintain it after I can no longer do so.

**Comment by Aqa-Ib** [comment]
Impressive. Hats off. 
My best wishes for you.
Cheers!
