### ISSUE TITLE
make error on Rocky Linux

### ISSUE THREAD

**Issue by Kirutian** [lwfinger/rtl8723du#17]
/home/user/rtl8723du/os_dep/linux/os_intfs.c:1855:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, void *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, void *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/home/user/rtl8723du/os_dep/linux/os_intfs.c:1855:22: note: (near initialization for ‘rtw_netdev_ops.ndo_select_queue’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:316: /home/user/rtl8723du/os_dep/linux/os_intfs.o] Error 1
make[1]: *** [Makefile:1571: _module_/home/user/rtl8723du] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-348.12.2.el8_5.x86_64'
make: *** [Makefile:2462: modules] Error 2

**Comment by lwfinger** [comment]
The code that is there matches a vanilla 4.18 kernel. Your must be modified. Please run the command 

find /usr/src/ -name netdevice.h

You should get a result that ends in include/linux/netdevice.h. Use that name as <file_name> in the command 'grep -a 3 ndo_select_queue <file_name>' and post that output.
