### ISSUE TITLE
Which branch of the driver should we use

### ISSUE THREAD

**Issue by eugenesan** [lwfinger/rtl8723du#18]
First, thank you very much for this driver.

I wonder which branch of the driver should we use?
5.13.4 seems to be more recent from Realtek and contains significantly more code but both branches being maintained making the choice confusing.

Thanks.

**Comment by lwfinger** [comment]
If one of them works for you, use it. Yes, v5.13.4 is later, but it may require kernel features that are not in the system that you run, and it takes a lot more memory, which may not be available on some SBC systems. That is why created a second branch for it.
