### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ba7bc87d-7c84-4862-8957-90c9aa6b2df2** [lwfinger/rtl8723du#20]
The rtw_proc.c file gives an error when compiling
![Screenshot_2022-05-11_00-16-29](https://user-images.githubusercontent.com/97496829/167774378-2f43279c-94ec-47d8-8a44-113323325292.png)

**Comment by lwfinger** [comment]
Fixed. Do a 'git pull'.

It is much simpler to copy-and-paste the error from the terminal to the GitHub page than it is to take a screen shot and attach it. I had a hard time reading your error, particularly with that black background in terminal.
