### ISSUE TITLE
the network connects but no connection

### ISSUE THREAD

**Issue by ba7bc87d-7c84-4862-8957-90c9aa6b2df2** [lwfinger/rtl8723du#23]
Hello, good afternoon

I am having a little problem with the driver, it seems that the network card connects successfully to my wi-fi but it does not give Internet I try to do the ping command, but it shows that the network is inaccessible 

I have no idea what could be causing the problem, I await your response, thanks.

**Comment by uDust** [comment]
I already managed to solve it, I only had the network card turned off, sorry for the inconvenience, thanks for your attention.

**Comment by ba7bc87d-7c84-4862-8957-90c9aa6b2df2** [comment]
I already managed to solve it, I only had the network card turned off, sorry for the inconvenience, thanks for your attention.
