### ISSUE TITLE
Incorrect Arch Install Instructions

### ISSUE THREAD

**Issue by Swivelgames** [lwfinger/rtl8723du#25]
The README lists:

> ```
> git clone https://aur.archlinux.org/rtw89-dkms-git.git
> cd rtw89-dkms-git
> makepkg -sri
> ```

But `rtw89-dkms-git` is [a different package](https://github.com/lwfinger/rtw89).

**Comment by lwfinger** [comment]
Below that are the correct installation instructions for all distros. I have removed the confusing ARCH instructions.
