### ISSUE TITLE
Error: While installing on EndeavourOS

### ISSUE THREAD

**Issue by ARBoyGo** [lwfinger/rtl8723du#37]
Error when installing on EndeavourOS(Arch) 
```
[arboygo@arboygo-pc rtl8723du]$ sudo make install
[sudo] password for arboygo: 
/bin/sh: line 1: bc: command not found
/bin/sh: line 1: echo: write error: Broken pipe
Makefile:2541: warning: overriding recipe for target 'sign'
Makefile:2476: warning: ignoring old recipe for target 'sign'
install -p -m 644 8723du.ko  /lib/modules/6.1.3-arch1-1/kernel/drivers/net/wireless/
/sbin/depmod -a 6.1.3-arch1-1
[arboygo@arboygo-pc rtl8723du]$ sudo modprobe -rv 8723du 
[arboygo@arboygo-pc rtl8723du]$ sudo modprobe -v 8723du
insmod /lib/modules/6.1.3-arch1-1/kernel/net/wireless/cfg80211.ko.zst 
insmod /lib/modules/6.1.3-arch1-1/kernel/drivers/net/wireless/8723du.ko 
```

**Comment by yetanothergeek** [comment]
Maybe run:
`sudo pacman -S bc`
and then try again.

**Comment by ARBoyGo** [comment]
Bc is solved,
But 
```
[arboygo@arboygo-pc rtl8723du]$ sudo make install
Makefile:2541: warning: overriding recipe for target 'sign'
Makefile:2476: warning: ignoring old recipe for target 'sign'
install -p -m 644 8723du.ko  /lib/modules/6.1.3-arch1-1/kernel/drivers/net/wireless/
/sbin/depmod -a 6.1.3-arch1-1
```
Bluethooth and wifi still not working.

**Comment by lwfinger** [comment]
That mesage has nothing to do with the devices not working. It is just a harmless warning from make. Similarly, the missing bc had no effect.

Run the command 'lsusb' and post the output.

**Comment by ARBoyGo** [comment]
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 020: ID 1ea7:0066 SHARKOON Technologies GmbH [Mediatrack Edge Mini Keyboard]
Bus 001 Device 015: ID 0bda:c820 Realtek Semiconductor Corp. 802.11ac NIC
Bus 001 Device 054: ID 2717:ff88 Xiaomi Inc. Mi/Redmi series (RNDIS + ADB)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by lwfinger** [comment]
My records show that your chip is an RTW8821CU. You are using the wrong driver.

The repo at https://githud.com/lwfinger/rtw88.git has a driver for that chip.

Note: I see no indication that the chip has BT capability.

**Comment by ARBoyGo** [comment]
> Note: I see no indication that the chip has BT capability.

But in windows it has BT capability.

**Comment by lwfinger** [comment]
With BT capability, at least with a USB interface, then 'lsusb' should show
Bus 003 Device 003: ID 0bda:887b Realtek Semiconductor Corp. Bluetooth Radio

That is the code for the RTW8852BE installed on my nachine. If it uses a serial interface to the BT, I do not support that.
