### ISSUE TITLE
RTL8723DU Wifi Driver Add to Mainline Linux Kernel

### ISSUE THREAD

**Issue by mo123** [lwfinger/rtl8723du#9]
Hi

Is there any way to get this RTL8723DU wifi driver into the mainline Linux kernel or ask Realtek for help?
So many ARM boards use this wifi and they use mainline Linux kernel then the wifi doesn't work out of the box.
Some Linux OS's like LibreELEC, users can't manually install extra wifi drivers, only when this OS is build from source since it uses mainline Linux kernel, they also don't want to use out of tree wifi drivers and want the wifi drivers to be added to the mainline Linux kernel.
Hope it would be possible one day as it would solve a lot of problems.

**Comment by lwfinger** [comment]
All of the Realtek drivers for USB devices would require much work to get the code into the condition required for submission to the kernel. So far, no one has volunteered to put forward this effort. For me, with considerable experience, I estimate 6-8 months full time. At this point in my life, I am not willing to this much.
